### ISSUE TITLE
关于运行的请教

### ISSUE THREAD

**Issue by xiayouhong** [chujiezheng/Click#1]
您好，请问您用的torch，python版本都是啥呢，我这边安装的最新版运行总是报错
![1708845354076](https://github.com/chujiezheng/Click/assets/61572755/2a272a0e-82cf-4bda-a80e-69228544fd43)

**Comment by chujiezheng** [comment]
My torch version was 1.12 and cuda is 10.2.

You may consider to downgrade `accelerate` to some old version (about release in late 2022, such as 0.14/0.15/0.16), and install compatible `transformers`

**Comment by xiayouhong** [comment]
Thank you! I'll give it a try.

**Comment by xiayouhong** [comment]
![image](https://github.com/chujiezheng/Click/assets/61572755/c9cbf2d3-91ff-4ee4-9b4f-1357956ff45c)
请问您有没有碰到过这个问题 “我已经安装了nltk，但是运行的时候找不到该模块，终端进入python后import nltk又是不报错的”

**Comment by chujiezheng** [comment]
Seems that you did not activate the environment properly

**Comment by xiayouhong** [comment]
![image](https://github.com/chujiezheng/Click/assets/61572755/cd76cd72-776a-4921-b85f-d6a7022f9934)
这样激活感觉没啥问题，虚拟环境中nltk也确实存在

**Comment by xiayouhong** [comment]
您好，您能分享一下您的虚拟环境中的requirements.txt吗，我这个一直不停地报错呢

**Comment by xiayouhong** [comment]
![image](https://github.com/chujiezheng/Click/assets/61572755/4d8c7139-7f38-4693-a35a-46f55c6eaa2d)
您好，在这个sh文件中，第22行里的这个augment_both.sh 在仓库里并没有看到

**Comment by chujiezheng** [comment]
This line may be invalid. Just removed it

**Comment by xiayouhong** [comment]
![image](https://github.com/chujiezheng/Click/assets/61572755/2fd688c9-16cd-4376-8532-877827601fa

**Comment by xiayouhong** [comment]
![1709797586582](https://github.com/chujiezheng/Click/assets/61572755/f524e5ff-8607-4a91-9af2-2214ee10b3af)

**Comment by xiayouhong** [comment]
![image](https://github.com/chujiezheng/Click/assets/61572755/6d15d839-e2b3-4355-993a-90a2688826ec)

**Comment by xiayouhong** [comment]
您好，请问你能帮我梳理一下这里的逻辑吗？感谢

**Comment by chujiezheng** [comment]
> ![image](https://private-user-images.githubusercontent.com/61572755/310789948-6d15d839-e2b3-4355-993a-90a2688826ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3OTc5NjAsIm5iZiI6MTcwOTc5NzY2MCwicGF0aCI6Ii82MTU3Mjc1NS8zMTA3ODk5NDgtNmQxNWQ4MzktZTJiMy00MzU1LTk5M2EtOTBhMjY4ODgyNmVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDA3NDc0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2N2IwMjJhNmIzMmI4MzEwMDM4YWRkNjUwZTA0MmQ4NTYyNzlkMWJlZGUyNGJjYWQ4MGM2OGY2MTdjOWFmNDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Um4tZ1zK8vrPpEeLp7qZ0L-3sA4Y3AfDGBfclOon-YE)

This line reads the losses of the ground truth responses. I think they would be computed after removing this line: https://github.com/chujiezheng/Click/blob/494e90434e76432a4b1da65fb2efe1dd992ebeba/scripts_bad/blender/augment.sh#L14

**Comment by xiayouhong** [comment]
thank you

**Comment by xiayouhong** [comment]
![image](https://github.com/chujiezheng/Click/assets/61572755/5914c132-9311-41ef-be99-25c0bd2df287)

您好，在复现论文的过程中，实验结果中的ppl比原文高了很多，实验几次的结果也都是这样，由于模型训练的数据集每次构造时是不一样的，能麻烦您提供一下您训练情感模型的数据集，我试试用您构造的训练集试一下看看ppl是否还会这么 高

**Comment by xiayouhong** [comment]
您好，我在复现过程中，发现最终结果中的ppl和论文中的结果差了30，其他的都很接近。是有什么原因吗？

**Comment by xiayouhong** [comment]
我按照github上的步骤运行，没有对代码有改动，我担心是click消融实验中构造数据对造成的影响，但是我把处理完的数据打印出来发现数据也没有啥问题

**Comment by xiayouhong** [comment]
![image](https://github.com/chujiezheng/Click/assets/61572755/29522c4e-7e2a-4c55-9bc9-07f61432889f)
这是我复现的实验结果

**Comment by chujiezheng** [comment]
Are the ppl values calculated using the larger GPT-2 XL model?

**Comment by xiayouhong** [comment]
yes

**Comment by xiayouhong** [comment]
我用您上传的模型进行推理，然后测试，和您论文的结果一样；用您上传的训练数据，先训练再推理，然后测试得到结果中ppl如上图所示

**Comment by chujiezheng** [comment]
I personally think this may result from the changes in the relied packages (like transformers and accelerate)... Sorry that I did not save the original running environment :(

**Comment by xiayouhong** [comment]
thanks

**Comment by xiayouhong** [comment]
但是只有ppl异常，是不是训练脚本有什么问题呀

**Comment by xiayouhong** [comment]
Can you provide me with some training log files so that I can compare them?

**Comment by chujiezheng** [comment]
Sorry that I did not save the training logs. If PPL is truly bad, it may not make sense that other metrics are good. Maybe you can double-check the input texts for calculating PPL (like tokenization and space, truncation length, etc.).

**Comment by xiayouhong** [comment]
我又尝试复现去毒的任务，并把去毒任务里的baseline也都跑了一遍，第一个问题是ppl呈现整体上升的趋势，baseline的ppl也比论文中的结果高百分之五十左右。 复现过程论文中的方法用在去毒上 ，我得到结果得到的毒性竟然高达0.7（论文中的结果是0.08），比baseline中non-tox的0.45还要高。
